title: Intro to Web Development
logo: https://image.freepik.com/free-vector/binary-code-netwrok-technology-concept-background_1017-13992.jpg
description: Learn what makes a website.
show_downloads: false
see_module_1: true
see_module_2: true
see_module_3: false
theme: jekyll-theme-minimal
baseurl: /intro-to-web-dev